security.basic.enabled: false

server.contextPath: /
server.port: 8080

management:
    port: 8081
    context-path: /management
    security.enabled: false
    health.redis.enabled: false



spring:
   application:
      name: demo
   datasource:
      url: jdbc:h2:mem:db;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
      testOnBorrow: true
      validationQuery: select 1
      password:
      username: sa
   jpa.hibernate.ddl-auto: create-drop
#   jpa.hibernate.ddl-auto: validate
   aop.proxyTargetClass: true
   h2.console.enabled: true
   redis:
       host: 127.0.0.1
       timeout: 5000
   cloud:
       consul:
         port: 8500
         host: 127.0.0.1
         discovery:
           enabled: true
           health-check-path: ${management.context-path}/health
           instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
           healthCheckInterval: 25s
#           heartbeat.enabled: false
           prefer-ip-address:  true
#           register: false
#           registerHealthCheck: false


   main:
        banner-mode: off
        show-banner: off

   metrics:
       export:
          redis:
             prefix: metrics.mysystem.${spring.application.name:application}.${random.value:0000}
             key: keys.metrics.mysystem
